### ISSUE TITLE
"Backus-Naur Form" images in README not shown

### ISSUE THREAD

**Issue by R0bari** [objectionary/eo#2706] opened 2023-12-17 11:11 UTC
Problems with images in README. Section "Backus-Naur Form". Tried to open in new tab - just white space/white box.
![image not displayed 1](https://github.com/objectionary/eo/assets/56538398/de3a8285-5bbc-4dbf-95fc-5e9a1d694d8f)
![image not displayed 2](https://github.com/objectionary/eo/assets/56538398/aea1a90e-5de6-42ee-b4f7-f7d47e64f574)

**Comment by yegor256** [comment] 2023-12-17 11:19
duplicate of #2696

**Comment by yegor256** [comment] 2023-12-17 11:20
@R0bari thanks for reporting! This happens because of version mismatch of the `convert` tool in Ubuntu. I will try to fix it soon.

**Closed by yegor256** 2023-12-17 11:19 UTC
