### ISSUE TITLE
`cage` attributes are not updated

### ISSUE THREAD

**Issue by advasileva** [objectionary/eo#1834] opened 2023-02-23 10:06 UTC
# Problem

I want to write an iterator using a `cage` object (no `memory`). Ideologically, something like this should work:
```eo
[s] > counter
  cage s > k
  [] > next
    seq > @
      ^.k.write (^.k.@.plus 1)
      ^.k
```

But such an iterator always returns `s+1`.  I do not know why. I guess the problem is with the `plus` attribute, which is taken by reference to the very first `s` value in the `counter`.

### Program
```eo
[s] > counter
  cage s > k
  [] > next
    seq > @
      QQ.io.stdout
        QQ.txt.sprintf
          "Was: %d\t"
          ^.k
      QQ.io.stdout
        QQ.txt.sprintf
          "Plus: %d\t"
          ^.k.@.plus 1
      ^.k.write (^.k.@.plus 1)
      QQ.io.stdout
        QQ.txt.sprintf
          "Written: %d\n"
          ^.k
      ^.k

[] > app
  counter 0 > c
  seq > @
    QQ.io.stdout
      QQ.txt.sprintf
        "First: %d\nSecond: %d\n"
        c.next
        c.next
```

### Runs with
```bash
eoc clean
eoc link
eoc --alone dataize app
```

### Expected:
```
Was: 0  Plus: 1 Written: 1
Was: 1  Plus: 2 Written: 2
First: 1
Second: 2
```

### Actual:
```
Was: 0  Plus: 1 Written: 1
Was: 1  Plus: 1 Written: 1
First: 1
Second: 1
```

**Comment by volodya-lombrozo** [comment] 2023-03-02 14:08
@advasileva 
It it the answer to your question?
> @volodya-lombrozo the `cage.write x` atom saves x, while the `memory.write x` atom dataizes the provided x first and then saves the bytes into the memory. The cage is lazy, while the memory is eager.

We already discussed something similar [here](https://github.com/objectionary/eo/issues/1698)

**Comment by advasileva** [comment] 2023-03-04 14:06
@volodya-lombrozo Yes, but it seems to me that this behavior is illogical. Can I close this issue as a duplicate?

**Comment by volodya-lombrozo** [comment] 2023-03-05 06:51
Duplicate of #1698

**Closed by volodya-lombrozo** 2023-03-05 06:51 UTC
