### ISSUE TITLE
apply new style of sorting `meta` to native objects

### ISSUE THREAD

**Issue by IngeniariusSoftware** [objectionary/eo#971] opened 2022-08-01 11:41 UTC
on version [0.26.0](https://github.com/objectionary/eo/tree/0.26.0), meta information in native objects still remains unsorted:

![image](https://user-images.githubusercontent.com/33983579/182139975-3171f468-87ab-4aa3-9dea-f0ddcc39f3cf.png)

**Comment by Graur** [comment] 2022-08-03 09:34
@IngeniariusSoftware I think pull request #960 will fix this issue when it is merged.

**Comment by yegor256** [comment] 2022-08-03 11:34
Duplicate of #846

**Closed by yegor256** 2022-08-03 11:34 UTC
