### ISSUE TITLE
Dataization fails for program from README

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#1477] opened 2022-11-21 11:58 UTC
I've created the program from README:
```eo
[] > app
  QQ.io.stdout > @
    QQ.txt.sprintf
      "Hello, %s!"
      "Jeffrey"
```

Then run the next command:
```sh
eoc clean
eoc dataize app
```
And I get the next error:
```
EO version is 0.28.11
EO objects registered in /Users/lombrozo/Workspace/EOlang/Projects/newcomer/.eoc/eo-foreign.json
EO version is 0.28.11
EO program assembled in /Users/lombrozo/Workspace/EOlang/Projects/newcomer/.eoc
EO version is 0.28.11
Java sources generated in /Users/lombrozo/Workspace/EOlang/Projects/newcomer/.eoc/generated-sources
EO version is 0.28.11
Java .class files compiled into /Users/lombrozo/Workspace/EOlang/Projects/newcomer/.eoc
EO version is 0.28.11
Executable JAR created at /Users/lombrozo/Workspace/EOlang/Projects/newcomer/.eoc/eoc.jar
EOorg.EOeolang.EOstringν21="Error at "EOorg.EOeolang.EOio.EOstdout#text" attribute; caused by Can't #copy() package object 'org.eolang.txt.sprintf'"SF
```

The problem: **EOorg.EOeolang.EOstringν21="Error at "EOorg.EOeolang.EOio.EOstdout#text" attribute; caused by Can't #copy() package object 'org.eolang.txt.sprintf'"SF**

**Comment by mximp** [comment] 2022-11-22 08:21
@volodya-lombrozo it's a known issue: https://github.com/objectionary/eo/issues/1323
You cannot use fully qualified names in the code for now.

**Comment by yegor256** [comment] 2022-12-07 07:43
Duplicate of #1323

**Closed by yegor256** 2022-12-07 07:43 UTC
