### ISSUE TITLE
Speed Up The Local Build

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#3705] opened 2024-12-19 08:56 UTC
I've tried to add some changes to the `objectionary/eo` repository and have faced with a significant problem. When I check new changes I run `mvn clean install -Pqulice` and get the following results:

```
[INFO] eo ................................................. SUCCESS [ 49.668 s]
[INFO] eo-parser .......................................... SUCCESS [ 27.204 s]
[INFO] eo-maven-plugin .................................... SUCCESS [02:03 min]
[INFO] eo-runtime ......................................... SUCCESS [23:27 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

As you can see, the entire build takes ~ `25 min` which makes it impossible to use. Please, speed up the local build.

**Comment by volodya-lombrozo** [comment] 2024-12-19 08:56
@yegor256 What do you think?

**Comment by yegor256** [comment] 2024-12-19 09:02
@volodya-lombrozo on CI we run it for 16 minutes: https://github.com/objectionary/eo/actions/runs/12408051847/job/34639067212 On my laptop it takes 10 minutes:

```
[INFO] eo ................................................. SUCCESS [ 15.209 s]
[INFO] eo-parser .......................................... SUCCESS [ 12.792 s]
[INFO] eo-maven-plugin .................................... SUCCESS [ 56.710 s]
[INFO] eo-runtime ......................................... SUCCESS [08:10 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  09:35 min
[INFO] Finished at: 2024-12-18T14:28:13+03:00
[INFO] ------------------------------------------------------------------------
```

Anyway, it's too rather slow, but will definitely become faster after this: https://github.com/objectionary/eo/issues/3696 I believe, this ticket is a duplicate of that one.

**Closed by yegor256** 2024-12-19 09:02 UTC
