### ISSUE TITLE
Cannot find cached files

### ISSUE THREAD

**Issue by Karina5005** [objectionary/eo#1130] opened 2022-08-31 12:37 UTC
I wanted to test the case where the build happens first and then the tests run without clearing the cache. But I get a compilation error in module `eo-runtime`.
I run:
```
mvn clean install
mvn test
```
Result:
```
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/karina/eo/eo-runtime/target/generated-sources/EOorg/EOeolang/EOmath/EOnumber.java:[366,21] cannot find symbol
  symbol:   class EOnumber$EOpow
  location: class EOorg.EOeolang.EOmath.EOnumber
[ERROR] /home/karina/eo/eo-runtime/target/generated-sources/EOorg/EOeolang/EOmath/EOnumber.java:[371,21] cannot find symbol
  symbol:   class EOnumber$EOas_float
  location: class EOorg.EOeolang.EOmath.EOnumber
[ERROR] /home/karina/eo/eo-runtime/target/generated-sources/EOorg/EOeolang/EOmath/EOnumber.java:[376,21] cannot find symbol
  symbol:   class EOnumber$EOas_int
  location: class EOorg.EOeolang.EOmath.EOnumber
[ERROR] /home/karina/eo/eo-runtime/target/generated-sources/EOorg/EOeolang/EOmath/EOnumber.java:[381,21] cannot find symbol
  symbol:   class EOnumber$EOas_string
  location: class EOorg.EOeolang.EOmath.EOnumber
[ERROR] /home/karina/eo/eo-runtime/target/generated-sources/EOorg/EOeolang/EOmath/EOangle.java:[83,21] cannot find symbol
  symbol:   class EOangle$EOsin
  location: class EOorg.EOeolang.EOmath.EOangle
[ERROR] /home/karina/eo/eo-runtime/target/generated-sources/EOorg/EOeolang/EOmath/EOangle.java:[88,21] cannot find symbol
  symbol:   class EOangle$EOcos
  location: class EOorg.EOeolang.EOmath.EOangle
[ERROR] /home/karina/eo/eo-runtime/target/generated-sources/EOorg/EOeolang/EOmath/EOrandom.java:[48,21] cannot find symbol
  symbol:   class EOrandom$EOpseudo
  location: class EOorg.EOeolang.EOmath.EOrandom
[ERROR] /home/karina/eo/eo-runtime/target/generated-sources/EOorg/EOeolang/EOcollections/EOmultimap.java:[206,21] cannot find symbol
  symbol:   class EOmultimap$EOrebuild
  location: class EOorg.EOeolang.EOcollections.EOmultimap
```

**Comment by yegor256** [comment] 2022-08-31 15:14
@Karina5005 definitely a bug, will take care of this

**Comment by yegor256** [comment] 2022-09-10 04:11
@mximp maybe you can help? The problem is related to `UnplaceMojo` and `TranspileMojo`. At `mvn install` phase we unplace some `*.class` files. Then, at `mvn test` we don't compile them again. Maybe this will be fixed by #1172 (or related to it).

**Comment by mximp** [comment] 2022-09-21 08:07
I'm on it

**Comment by mximp** [comment] 2022-09-22 07:44
@yegor256 what is the point of deleting pulled classes in `UnplaceMojo`?

**Comment by mximp** [comment] 2022-09-22 07:51
@yegor256 and what is so special about these libs specified for deletion:
```
<removeBinaries>
                <glob>EOorg/EOeolang/EOhamcrest/**</glob>
                <glob>EOorg/EOeolang/EOmath/**</glob>
                <glob>EOorg/EOeolang/EOfs/**</glob>
              </removeBinaries>
```

**Comment by mximp** [comment] 2022-09-29 06:32
@Karina5005 this is fixed now. Please verify and close the task

**Comment by mximp** [comment] 2022-10-04 11:51
Closing as resolved

**Closed by mximp** 2022-10-04 11:51 UTC
Labels: bug
