### ISSUE TITLE
Access to attribute without dataization

### ISSUE THREAD

**Issue by someilay** [objectionary/eo#736] opened 2022-06-14 10:17 UTC
Code:
```
[value] > number
  "number" > @

[x] > inc
  seq > @
    x.value.write (x.value.add 1)
    x

[args...] > main
  cage (inc (number (memory 0))) > my_object
  seq > @
    println (my_object.value)
    println (my_object.value)
```

It prints twice `1`. It is kinda strange for me because I expect that each access to `value` leads to dataizaation of `inc.@`. However, it doesn't happen at all. @yegor256, can you explain why?

**Comment by yegor256** [comment] 2022-06-15 09:54
@someilay what happens if you remove `number`? still the same problem?

**Comment by someilay** [comment] 2022-06-15 13:03
@yegor256. What do you mean by removing `number`?

**Comment by someilay** [comment] 2022-06-15 14:22
@yegor256. Bug disapears in this case

**Comment by someilay** [comment] 2022-06-16 10:10
@yegor256. Is it a bug?

**Comment by yegor256** [comment] 2022-06-16 15:04
@someilay it seems to be a bug, but I'm not sure. The example is pretty complex, hard to tell whether your code is broken or the language is broken. I tried to invent a simpler example, but failed so far. If you can make a simpler one, it would help.

**Comment by yegor256** [comment] 2022-06-17 15:26
@someilay not yet... working on it

**Comment by someilay** [comment] 2022-06-23 13:12
@yegor256. Did you achieve a result?

**Comment by yegor256** [comment] 2022-09-08 15:17
@Graur please, try to investigate and help

**Comment by Graur** [comment] 2022-09-09 13:28
This problem is still here. I tried to simplify this test and it printed `1` twice:
```
[] > test
  [value] > second
    value.plus 1 > @

  [] > @
    second 1 > first
    seq > @
      QQ.io.stdout
        QQ.txt.sprintf
          "%d"
          first.value
      first
      QQ.io.stdout
        QQ.txt.sprintf
          "%d"
          first.value
```
@yegor256 Should `first.value` dataize `first` and only after call `value` method? Or it is ok, that `first.value` just call `value` from `first` and that's it?

**Comment by yegor256** [comment] 2022-09-09 14:19
@Graur if `.value` is found, `first.@` won't be dataized. If `.value` is absent, `first.@` will be dataized.

**Comment by Graur** [comment] 2022-09-09 14:48
@yegor256 Thanks! So the next step is to figure out should `.value` be dataized in this cases twice? Now it happens only once

**Comment by yegor256** [comment] 2022-09-09 19:22
@Graur yes, should print twice. I suggest to try to make this code snippet smaller, to narrow the area of the bug.

**Comment by Graur** [comment] 2022-09-09 19:30
@yegor256 @someilay If it's not a bug, let's close this ticket

**Closed** 2022-09-20 19:40 UTC
Labels: bug
