### ISSUE TITLE
Can't `unphi` normalized programs

### ISSUE THREAD

**Issue by deemp** [objectionary/eo#3212] opened 2024-06-05 09:39 UTC
@yegor256, @maxonfjvipon

## Problem

I converted a EO program ([link](https://github.com/objectionary/eo/blob/c4fe24fc2359957261b1e56b8cac9113d0b77db2/eo-runtime/src/test/eo/org/eolang/as-phi-tests.eo)) to a PHI program, normalized the PHI program, tried to convert the normalized PHI program to EO and got an error.

Possibly related issue - https://github.com/objectionary/eoc/issues/293

## Programs

N.B. programs come from the pipeline artifact ([link](https://github.com/user-attachments/files/15585116/pipeline-files-Linux.11.zip)) produced in the `objectionary/normalizer` repo ([link](https://github.com/objectionary/normalizer/actions/runs/9370678335)).

### as-phi-tests.eo

`pipeline/eo-initial/as-phi-tests.eo` - initial EO program:

```
+alias org.eolang.io.stdout
+architect yegor256@gmail.com
+home https://github.com/objectionary/eo
+tests
+package org.eolang
+version 0.0.0

# Test.
[] > prints-itself
  gt. > @
    length.
      as-phi $
    0

# Test.
[] > prints-itself-to-console
  42 > x
  stdout > @
    as-phi $
```

`pipeline/phi-initial/as-phi-tests.phi` - non-normalized PHI program:

```
{
  ⟦
    org ↦ ⟦
      eolang ↦ ⟦
        prints-itself ↦ ⟦
          φ ↦ Φ.org.eolang.as-phi(
            α0 ↦ ξ
          ).length.gt(
            α0 ↦ Φ.org.eolang.int(
              α0 ↦ Φ.org.eolang.bytes(
                Δ ⤍ 00-00-00-00-00-00-00-00
              )
            )
          )
        ⟧,
        prints-itself-to-console ↦ ⟦
          x ↦ Φ.org.eolang.int(
            α0 ↦ Φ.org.eolang.bytes(
              Δ ⤍ 00-00-00-00-00-00-00-2A
            )
          ),
          φ ↦ Φ.org.eolang.io.stdout(
            α0 ↦ Φ.org.eolang.as-phi(
              α0 ↦ ξ
            )
          )
        ⟧,
        λ ⤍ Package
      ⟧,
      λ ⤍ Package
    ⟧
  ⟧
}
```

`pipeline/phi-normalized/as-phi-tests.phi` - normalized PHI program:

(original)

```
{ ⟦ org ↦ ⟦ eolang ↦ ⟦ prints-itself ↦ Φ.org.eolang.as-phi (α0 ↦ ξ).length.gt (α0 ↦ Φ.org.eolang.int (α0 ↦ Φ.org.eolang.bytes (Δ ⤍ 00-00-00-00-00-00-00-00))), prints-itself-to-console ↦ Φ.org.eolang.io.stdout (α0 ↦ Φ.org.eolang.as-phi (α0 ↦ ξ)), λ ⤍ Package ⟧, λ ⤍ Package ⟧, λ ⤍ Package ⟧ }
```

(formatted):

```
{
  ⟦
    org ↦ ⟦
      eolang ↦ ⟦
        prints-itself ↦
          Φ.org.eolang.as-phi(α0 ↦ ξ).length.gt(
            α0 ↦ Φ.org.eolang.int(
              α0 ↦ Φ.org.eolang.bytes(Δ ⤍ 00-00-00-00-00-00-00-00)
            )
          ),
        prints-itself-to-console ↦ Φ.org.eolang.io.stdout(
          α0 ↦ Φ.org.eolang.as-phi (α0 ↦ ξ)
        ),
        λ ⤍ Package
      ⟧,
      λ ⤍ Package
    ⟧,
    λ ⤍ Package
  ⟧
}
```

## Command

```
eoc unphi --tests
```

## Error

```
[ERROR] java.util.EmptyStackExceptionted so far...
[ERROR] Failed to execute goal org.eolang:eo-maven-plugin:0.38.0:phi-to-xmir (default-cli) on project eoc: 'org.eolang.maven.UnphiMojo@5f95f1e1' execution failed: java.io.UncheckedIOException: java.io.IOException: java.util.concurrent.ExecutionException: java.util.EmptyStackException -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
The command "/home/eyjafjallajokull/Desktop/gh/normalizer/node_modules/eolang/mvnw/mvnw eo:phi-to-xmir -Deo.version=0.38.0 -Deo.tag=0.38.0 --quiet -Deo.sourcesDir=/home/eyjafjallajokull/Desktop/gh/normalizer/pipeline/phi-normalized -Deo.targetDir=/home/eyjafjallajokull/Desktop/gh/normalizer/pipeline/phi-normalized/.eoc -Deo.outputDir=/home/eyjafjallajokull/Desktop/gh/normalizer/pipeline/phi-normalized/.eoc/classes -Deo.generatedDir=/home/eyjafjallajokull/Desktop/gh/normalizer/pipeline/phi-normalized/.eoc/generated-sources -Deo.placed=/home/eyjafjallajokull/Desktop/gh/normalizer/pipeline/phi-normalized/.eoc/eo-placed.csv -Deo.placedFormat=csv -Deo.unphiInputDir=/home/eyjafjallajokull/Desktop/gh/normalizer/pipeline/phi-normalized/.eoc/phi -Deo.unphiOutputDir=/home/eyjafjallajokull/Desktop/gh/normalizer/pipeline/phi-normalized/.eoc/unphi -Deo.unphiMetas=+tests --batch-mode --color=never --update-snapshots --fail-fast --strict-checksums" exited with #1 code
```

## Questions

How to correctly convert PHI program with tests to EO? I'd like to get answers for the following cases:

1. Case 1 - Initially, there are no `eoc`-specific directories. There's a file `as-phi-tests.phi` with the same content as `pipeline/phi-normalized/as-phi-tests.phi`.
1. Case 2 - Initially, there's `as-phi-tests.phi`  with the same content as `pipeline/phi-normalized/as-phi-tests.phi` and there's a `.eoc` produced by another `eoc` operation, e.g., `eoc phi`. I want to reuse this `.eoc` to run a script faster.

**Comment by maxonfjvipon** [comment] 2024-06-05 10:26
@deemp I strongly believe that:
```
prints-itself-to-console ↦ ⟦
  x ↦ Φ.org.eolang.int(
    α0 ↦ Φ.org.eolang.bytes(
      Δ ⤍ 00-00-00-00-00-00-00-2A
    )
  ),
  φ ↦ Φ.org.eolang.io.stdout(
    α0 ↦ Φ.org.eolang.as-phi(
      α0 ↦ ξ
    )
  )
⟧,
```
won't work the same way as:
```
prints-itself-to-console ↦ Φ.org.eolang.io.stdout(
  α0 ↦ Φ.org.eolang.as-phi (α0 ↦ ξ)
),
```

Because `ξ` refers to nearest formation. In the first object `ξ` refers to `prints-itself-to-console`, in the second it refers to `eolang`

**Comment by maxonfjvipon** [comment] 2024-06-05 10:30
@deemp and it seems our phi parser is not ready for such constructions where there's no any formation inside the object with `λ ⤍ Package`

**Comment by maxonfjvipon** [comment] 2024-06-05 10:33
@yegor256 please check this out:
We have such phi expression. We get it after normalization.
```
{
    ⟦
      org ↦ ⟦
        eolang ↦ ⟦
          prints-itself-to-console ↦ Φ.org.eolang.io.stdout(
            α0 ↦ Φ.org.eolang.as-phi (α0 ↦ ξ)
          ),
          λ ⤍ Package
        ⟧,
        λ ⤍ Package
      ⟧,
      λ ⤍ Package
    ⟧
  }
```
I don't see a way how it can to converted to EO. Do you?

**Comment by fizruk** [comment] 2024-06-05 10:35
> @deemp and it seems our phi parser is not ready for such constructions where there's no any formation inside the object with `λ ⤍ Package`

We can drop the top-level `λ ⤍ Package`, it is injected for technical reasons. Is the rest fine?

**Comment by maxonfjvipon** [comment] 2024-06-05 10:41
@fizruk I think so. Such example works fine:
```
{
  ⟦
    org ↦ ⟦
      eolang ↦ ⟦
        prints-itself ↦
          Φ.org.eolang.as-phi(α0 ↦ ξ).length.gt(
            α0 ↦ Φ.org.eolang.int(
              α0 ↦ Φ.org.eolang.bytes(Δ ⤍ 00-00-00-00-00-00-00-00)
            )
          ),
        prints-itself-to-console ↦ Φ.org.eolang.io.stdout(
          α0 ↦ Φ.org.eolang.as-phi (α0 ↦ ξ)
        ),
        λ ⤍ Package
      ⟧,
      λ ⤍ Package
    ⟧
  ⟧
}
```

**Comment by deemp** [comment] 2024-06-05 14:32
I can't `unphi` these normalized programs:

`malloc-tests.phi`

```
{ ⟦ org ↦ ⟦ eolang ↦ ⟦ writes-into-memory-of ↦ ξ.mem.eq (α0 ↦ Φ.org.eolang.int (α0 ↦ Φ.org.eolang.bytes (Δ ⤍ 00-00-00-00-00-00-00-0A))), puts-into-memory-for ↦ ξ.mem.eq (α0 ↦ Φ.org.eolang.int (α0 ↦ Φ.org.eolang.bytes (Δ ⤍ 00-00-00-00-00-00-00-0A))), malloc-scope-is-dataized-twice ↦ ⊥, malloc-for-writes-first-init-value ↦ Φ.org.eolang.malloc.for (α0 ↦ Φ.org.eolang.int (α0 ↦ Φ.org.eolang.bytes (Δ ⤍ 00-00-00-00-00-00-00-2A)), α1 ↦ ⟦ φ ↦ Φ.org.eolang.true, m ↦ ∅ ⟧).eq (α0 ↦ Φ.org.eolang.int (α0 ↦ Φ.org.eolang.bytes (Δ ⤍ 00-00-00-00-00-00-00-2A))), malloc-puts-over-the-previous-data ↦ ⊥, malloc-rewrites-and-increments-itself ↦ ξ.mem.eq (α0 ↦ Φ.org.eolang.int (α0 ↦ Φ.org.eolang.bytes (Δ ⤍ 00-00-00-00-00-00-00-06))), writes-into-two-malloc-objects ↦ ξ.a.eq (α0 ↦ Φ.org.eolang.int (α0 ↦ Φ.org.eolang.bytes (Δ ⤍ 00-00-00-00-00-00-00-0A))).and (α0 ↦ ξ.b.eq (α0 ↦ Φ.org.eolang.int (α0 ↦ Φ.org.eolang.bytes (Δ ⤍ 00-00-00-00-00-00-00-14)))), malloc-is-strictly-sized-bool-error-overflow ↦ Φ.org.eolang.try (α0 ↦ Φ.org.eolang.malloc.for (α0 ↦ Φ.org.eolang.false, α1 ↦ ⟦ φ ↦ ξ.m.put (α0 ↦ Φ.org.eolang.float (α0 ↦ Φ.org.eolang.bytes (Δ ⤍ 41-94-88-A5-0F-85-1E-B8))), m ↦ ∅ ⟧), α1 ↦ ⟦ φ ↦ Φ.org.eolang.io.stdout (α0 ↦ ξ.e), e ↦ ∅ ⟧, α2 ↦ Φ.org.eolang.false), malloc-is-strictly-sized-string-error-overflow ↦ Φ.org.eolang.try (α0 ↦ Φ.org.eolang.malloc.for (α0 ↦ Φ.org.eolang.string (α0 ↦ Φ.org.eolang.bytes (Δ ⤍ 48-65-6C-6C-6F)), α1 ↦ ⟦ φ ↦ ξ.m.put (α0 ↦ Φ.org.eolang.string (α0 ↦ Φ.org.eolang.bytes (Δ ⤍ 4D-75-63-68-20-6C-6F-6E-67-65-72-20-73-74-72-69-6E-67-21))), m ↦ ∅ ⟧), α1 ↦ ⟦ φ ↦ Φ.org.eolang.io.stdout (α0 ↦ ξ.e), e ↦ ∅ ⟧, α2 ↦ Φ.org.eolang.false), malloc-is-strictly-sized-int ↦ Φ.org.eolang.malloc.for (α0 ↦ Φ.org.eolang.int (α0 ↦ Φ.org.eolang.bytes (Δ ⤍ 00-00-00-00-00-00-2F-D8)), α1 ↦ ⟦ φ ↦ ξ.m.put (α0 ↦ Φ.org.eolang.int (α0 ↦ Φ.org.eolang.bytes (Δ ⤍ 00-00-00-00-00-00-09-FC))), m ↦ ∅ ⟧).eq (α0 ↦ Φ.org.eolang.int (α0 ↦ Φ.org.eolang.bytes (Δ ⤍ 00-00-00-00-00-00-09-FC))), malloc-is-strictly-typed-float ↦ Φ.org.eolang.malloc.for (α0 ↦ Φ.org.eolang.float (α0 ↦ Φ.org.eolang.bytes (Δ ⤍ 40-6E-BC-28-F5-C2-8F-5C)), α1 ↦ ⟦ φ ↦ ξ.m.put (α0 ↦ Φ.org.eolang.float (α0 ↦ Φ.org.eolang.bytes (Δ ⤍ 40-54-8E-14-7A-E1-47-AE))), m ↦ ∅ ⟧).eq (α0 ↦ Φ.org.eolang.float (α0 ↦ Φ.org.eolang.bytes (Δ ⤍ 40-54-8E-14-7A-E1-47-AE))), memory-is-strictly-sized-string ↦ Φ.org.eolang.malloc.for (α0 ↦ Φ.org.eolang.string (α0 ↦ Φ.org.eolang.bytes (Δ ⤍ 48-65-6C-6C-6F)), α1 ↦ ⟦ φ ↦ ξ.m.put (α0 ↦ Φ.org.eolang.string (α0 ↦ Φ.org.eolang.bytes (Δ ⤍ 50-72-6F-74))), m ↦ ∅ ⟧).eq (α0 ↦ Φ.org.eolang.string (α0 ↦ Φ.org.eolang.bytes (Δ ⤍ 50-72-6F-74-6F))), malloc-is-strictly-typed-bool ↦ ⟦ λ ⤍ Lorg_eolang_malloc_of_φ ⟧, malloc-gives-id-to-allocated-block ↦ ⟦ λ ⤍ Lorg_eolang_malloc_of_φ ⟧, malloc-allocates-right-size-block ↦ ⟦ λ ⤍ Lorg_eolang_malloc_of_φ ⟧, malloc-writes-and-reads ↦ ⟦ λ ⤍ Lorg_eolang_malloc_of_φ ⟧, malloc-concacts-strings-with-offset ↦ ⟦ λ ⤍ Lorg_eolang_malloc_of_φ ⟧, malloc-cant-write-more-than-allocated-with-offset ↦ Φ.org.eolang.try (α0 ↦ Φ.org.eolang.malloc.of (α0 ↦ Φ.org.eolang.int (α0 ↦ Φ.org.eolang.bytes (Δ ⤍ 00-00-00-00-00-00-00-01)), α1 ↦ ⟦ φ ↦ ξ.m.write (α0 ↦ Φ.org.eolang.int (α0 ↦ Φ.org.eolang.bytes (Δ ⤍ 00-00-00-00-00-00-00-01)), α1 ↦ Φ.org.eolang.true), m ↦ ∅ ⟧), α1 ↦ ⟦ φ ↦ Φ.org.eolang.io.stdout (α0 ↦ ξ.e), e ↦ ∅ ⟧, α2 ↦ Φ.org.eolang.false), malloc-reads-with-offset-and-length ↦ ⟦ λ ⤍ Lorg_eolang_malloc_of_φ ⟧, λ ⤍ Package ⟧, λ ⤍ Package ⟧ ⟧ }
```

`seq-tests.phi`

```
{ ⟦ org ↦ ⟦ eolang ↦ ⟦ seq-single-dataization-float-less ↦ ⟦ λ ⤍ Lorg_eolang_malloc_of_φ ⟧, seq-single-dataization-float-greater ↦ ⟦ λ ⤍ Lorg_eolang_malloc_of_φ ⟧, seq-single-dataization-int-less ↦ ⟦ λ ⤍ Lorg_eolang_malloc_of_φ ⟧, seq-single-dataization-int-less-or-equal ↦ ⟦ λ ⤍ Lorg_eolang_malloc_of_φ ⟧, very-long-seq ↦ ⊥, seq-single-dataization-int-equal-to-test ↦ ⟦ λ ⤍ Lorg_eolang_malloc_of_φ ⟧, seq-single-dataization-int-equal-to-cache-problem-test ↦ ⟦ λ ⤍ Lorg_eolang_malloc_of_φ ⟧, λ ⤍ Package ⟧, λ ⤍ Package ⟧  ⟧ }
```

`while-tests.phi`

```
{ ⟦ org ↦ ⟦ eolang ↦ ⟦ writes-into-memory-of ↦ ξ.mem.eq (α0 ↦ Φ.org.eolang.int (α0 ↦ Φ.org.eolang.bytes (Δ ⤍ 00-00-00-00-00-00-00-0A))), puts-into-memory-for ↦ ξ.mem.eq (α0 ↦ Φ.org.eolang.int (α0 ↦ Φ.org.eolang.bytes (Δ ⤍ 00-00-00-00-00-00-00-0A))), malloc-scope-is-dataized-twice ↦ ⊥, malloc-for-writes-first-init-value ↦ Φ.org.eolang.malloc.for (α0 ↦ Φ.org.eolang.int (α0 ↦ Φ.org.eolang.bytes (Δ ⤍ 00-00-00-00-00-00-00-2A)), α1 ↦ ⟦ φ ↦ Φ.org.eolang.true, m ↦ ∅ ⟧).eq (α0 ↦ Φ.org.eolang.int (α0 ↦ Φ.org.eolang.bytes (Δ ⤍ 00-00-00-00-00-00-00-2A))), malloc-puts-over-the-previous-data ↦ ⊥, malloc-rewrites-and-increments-itself ↦ ξ.mem.eq (α0 ↦ Φ.org.eolang.int (α0 ↦ Φ.org.eolang.bytes (Δ ⤍ 00-00-00-00-00-00-00-06))), writes-into-two-malloc-objects ↦ ξ.a.eq (α0 ↦ Φ.org.eolang.int (α0 ↦ Φ.org.eolang.bytes (Δ ⤍ 00-00-00-00-00-00-00-0A))).and (α0 ↦ ξ.b.eq (α0 ↦ Φ.org.eolang.int (α0 ↦ Φ.org.eolang.bytes (Δ ⤍ 00-00-00-00-00-00-00-14)))), malloc-is-strictly-sized-bool-error-overflow ↦ Φ.org.eolang.try (α0 ↦ Φ.org.eolang.malloc.for (α0 ↦ Φ.org.eolang.false, α1 ↦ ⟦ φ ↦ ξ.m.put (α0 ↦ Φ.org.eolang.float (α0 ↦ Φ.org.eolang.bytes (Δ ⤍ 41-94-88-A5-0F-85-1E-B8))), m ↦ ∅ ⟧), α1 ↦ ⟦ φ ↦ Φ.org.eolang.io.stdout (α0 ↦ ξ.e), e ↦ ∅ ⟧, α2 ↦ Φ.org.eolang.false), malloc-is-strictly-sized-string-error-overflow ↦ Φ.org.eolang.try (α0 ↦ Φ.org.eolang.malloc.for (α0 ↦ Φ.org.eolang.string (α0 ↦ Φ.org.eolang.bytes (Δ ⤍ 48-65-6C-6C-6F)), α1 ↦ ⟦ φ ↦ ξ.m.put (α0 ↦ Φ.org.eolang.string (α0 ↦ Φ.org.eolang.bytes (Δ ⤍ 4D-75-63-68-20-6C-6F-6E-67-65-72-20-73-74-72-69-6E-67-21))), m ↦ ∅ ⟧), α1 ↦ ⟦ φ ↦ Φ.org.eolang.io.stdout (α0 ↦ ξ.e), e ↦ ∅ ⟧, α2 ↦ Φ.org.eolang.false), malloc-is-strictly-sized-int ↦ Φ.org.eolang.malloc.for (α0 ↦ Φ.org.eolang.int (α0 ↦ Φ.org.eolang.bytes (Δ ⤍ 00-00-00-00-00-00-2F-D8)), α1 ↦ ⟦ φ ↦ ξ.m.put (α0 ↦ Φ.org.eolang.int (α0 ↦ Φ.org.eolang.bytes (Δ ⤍ 00-00-00-00-00-00-09-FC))), m ↦ ∅ ⟧).eq (α0 ↦ Φ.org.eolang.int (α0 ↦ Φ.org.eolang.bytes (Δ ⤍ 00-00-00-00-00-00-09-FC))), malloc-is-strictly-typed-float ↦ Φ.org.eolang.malloc.for (α0 ↦ Φ.org.eolang.float (α0 ↦ Φ.org.eolang.bytes (Δ ⤍ 40-6E-BC-28-F5-C2-8F-5C)), α1 ↦ ⟦ φ ↦ ξ.m.put (α0 ↦ Φ.org.eolang.float (α0 ↦ Φ.org.eolang.bytes (Δ ⤍ 40-54-8E-14-7A-E1-47-AE))), m ↦ ∅ ⟧).eq (α0 ↦ Φ.org.eolang.float (α0 ↦ Φ.org.eolang.bytes (Δ ⤍ 40-54-8E-14-7A-E1-47-AE))), memory-is-strictly-sized-string ↦ Φ.org.eolang.malloc.for (α0 ↦ Φ.org.eolang.string (α0 ↦ Φ.org.eolang.bytes (Δ ⤍ 48-65-6C-6C-6F)), α1 ↦ ⟦ φ ↦ ξ.m.put (α0 ↦ Φ.org.eolang.string (α0 ↦ Φ.org.eolang.bytes (Δ ⤍ 50-72-6F-74))), m ↦ ∅ ⟧).eq (α0 ↦ Φ.org.eolang.string (α0 ↦ Φ.org.eolang.bytes (Δ ⤍ 50-72-6F-74-6F))), malloc-is-strictly-typed-bool ↦ ⟦ λ ⤍ Lorg_eolang_malloc_of_φ ⟧, malloc-gives-id-to-allocated-block ↦ ⟦ λ ⤍ Lorg_eolang_malloc_of_φ ⟧, malloc-allocates-right-size-block ↦ ⟦ λ ⤍ Lorg_eolang_malloc_of_φ ⟧, malloc-writes-and-reads ↦ ⟦ λ ⤍ Lorg_eolang_malloc_of_φ ⟧, malloc-concacts-strings-with-offset ↦ ⟦ λ ⤍ Lorg_eolang_malloc_of_φ ⟧, malloc-cant-write-more-than-allocated-with-offset ↦ Φ.org.eolang.try (α0 ↦ Φ.org.eolang.malloc.of (α0 ↦ Φ.org.eolang.int (α0 ↦ Φ.org.eolang.bytes (Δ ⤍ 00-00-00-00-00-00-00-01)), α1 ↦ ⟦ φ ↦ ξ.m.write (α0 ↦ Φ.org.eolang.int (α0 ↦ Φ.org.eolang.bytes (Δ ⤍ 00-00-00-00-00-00-00-01)), α1 ↦ Φ.org.eolang.true), m ↦ ∅ ⟧), α1 ↦ ⟦ φ ↦ Φ.org.eolang.io.stdout (α0 ↦ ξ.e), e ↦ ∅ ⟧, α2 ↦ Φ.org.eolang.false), malloc-reads-with-offset-and-length ↦ ⟦ λ ⤍ Lorg_eolang_malloc_of_φ ⟧, λ ⤍ Package ⟧, λ ⤍ Package ⟧ ⟧ }
```

**Comment by maxonfjvipon** [comment] 2024-06-05 14:33
@deemp could you please format them?

**Comment by deemp** [comment] 2024-06-05 14:37
@maxonfjvipon, I can't format them now because pretty-printing isn't implemented yet (https://github.com/objectionary/normalizer/issues/292). Probably we implement this with @fizruk later in the evening

**Comment by maxonfjvipon** [comment] 2024-06-05 14:53
@deemp yes, I think the problem is in `⊥` sign, we can't properly convert to XMIR for now

**Comment by maxonfjvipon** [comment] 2024-06-05 14:54
@deemp btw, why this EO test which works:
```
# Test.
[] > while-dataizes-only-first-cycle
  eq. > @
    0
    malloc.for
      42
      [m]
        while > @
          i.eq 0 > [i]
          m.put i > [i] >>
```
after your normalization is converted to `while-dataizes-only-first-cycle ↦ ⊥`?

**Comment by maxonfjvipon** [comment] 2024-06-05 14:59
@deemp such case `x ↦ ⊥` will be translated to next EO:
```
org.eolang.error > x
  "Unknown error"
```
which is equal to: 
```
x ↦ Φ.org.eolang.error(
  α0 ↦ Φ.org.eolang.string(
    α0 ↦ Φ.org.eolang.bytes(Δ ⤍ ...)
  )
)
```

**Comment by fizruk** [comment] 2024-06-05 15:51
> @deemp btw, why this EO test which works:
> 
> ```
> # Test.
> [] > while-dataizes-only-first-cycle
>   eq. > @
>     0
>     malloc.for
>       42
>       [m]
>         while > @
>           i.eq 0 > [i]
>           m.put i > [i] >>
> ```
> 
> after your normalization is converted to `while-dataizes-only-first-cycle ↦ ⊥`?

Interesting. For this test the issue is that it gets stuck on `⟦ λ ⤍ Lorg_eolang_malloc_of_φ ⟧.as-bytes` when trying to dataize atom `Lorg_eolang_bytes_eq`. Normalizer currently thinks that this is a problem, since it cannot extract bytes from malloc (it does not know about malloc). Clearly, we should abort dataization and keep the original $\varphi$-term instead. The fix is on the way.

**Comment by fizruk** [comment] 2024-06-05 15:51
> @deemp I strongly believe that:
> 
> ```
> prints-itself-to-console ↦ ⟦
>   x ↦ Φ.org.eolang.int(
>     α0 ↦ Φ.org.eolang.bytes(
>       Δ ⤍ 00-00-00-00-00-00-00-2A
>     )
>   ),
>   φ ↦ Φ.org.eolang.io.stdout(
>     α0 ↦ Φ.org.eolang.as-phi(
>       α0 ↦ ξ
>     )
>   )
> ⟧,
> ```
> 
> won't work the same way as:
> 
> ```
> prints-itself-to-console ↦ Φ.org.eolang.io.stdout(
>   α0 ↦ Φ.org.eolang.as-phi (α0 ↦ ξ)
> ),
> ```
> 
> Because `ξ` refers to nearest formation. In the first example `ξ` refers to `prints-itself-to-console`, in the second it refers to `eolang`

Found the issue in dataization procedure, fix is on the way.

**Comment by fizruk** [comment] 2024-06-05 15:52
> @deemp and it seems our phi parser is not ready for such constructions where there's no any formation inside the object with `λ ⤍ Package`

Fixed in https://github.com/objectionary/normalizer/pull/392.

**Comment by fizruk** [comment] 2024-06-05 15:52
@maxonfjvipon Thanks a lot for the quick response in this thread. I have no further questions, I think this issue can be closed. @deemp ?

**Comment by maxonfjvipon** [comment] 2024-06-05 16:00
@fizruk @deemp I think it should be resolved and the ticket may be closed:
> @deemp such case x ↦ ⊥ will be translated to next EO:
>```
>org.eolang.error > x
>  "Unknown error"
>```
>which is equal to:
>
>```
>x ↦ Φ.org.eolang.error(
>  α0 ↦ Φ.org.eolang.string(
>    α0 ↦ Φ.org.eolang.bytes(Δ ⤍ ...)
>  )
>)
>```

**Closed** 2024-06-17 09:21 UTC
