### ISSUE TITLE
Strange return of "while." object

### ISSUE THREAD

**Issue by MikhailLipanin** [objectionary/eo#1192] opened 2022-09-07 15:22 UTC
I have a simple program:
```
+alias org.eolang.txt.sprintf
+alias org.eolang.io.stdout

[] > app
  memory 0 > x
  seq > @
    while. > remind!
      x.lt 3
      [i]
        seq > @
          x.write (x.plus 1)
          x
    stdout
      sprintf
        "out is %d\n"
        remind
```
which works good and as a result, it will return the following string:
```
out is 3
```
BUT, if i remove `!` symbol from name `remind` of object `while.`, result of dataization of object `while.` becomes `boolean` object.
So, for this code:
```
+alias org.eolang.txt.sprintf
+alias org.eolang.io.stdout

[] > app
  memory 0 > x
  seq > @
    while. > remind
      x.lt 3
      [i]
        seq > @
          x.write (x.plus 1)
          x
    stdout
      sprintf
        "out is %b\n"
        remind
```
Output appears as:
```
out is false
```

Based on documentation of new dataization of object `while.`, it returns `false` only if it's condition has never been TRUE, but
in this case I haven't changed condition.

@yegor256 this is a bug or not?

**Comment by Graur** [comment] 2022-09-07 15:29
@MikhailLipanin Maybe it could be a double dataization of `remind` object

**Comment by MikhailLipanin** [comment] 2022-09-07 15:32
@Graur, but when we have any object with 'name', and it was already been dataized, 
is it right, that in this case we only get result of dataization via its `name` and not dataize this object again?

**Comment by yegor256** [comment] 2022-09-07 18:05
@MikhailLipanin in the second snippet, `seq` first dataizes the object `remind` and _then_ dataizes the object `stdout`, which of course _again_ dataizes the `remind`

**Comment by yegor256** [comment] 2022-09-19 18:47
@MikhailLipanin I think it's not a bug, I'm closing

**Closed by yegor256** 2022-09-19 18:47 UTC
