### ISSUE TITLE
one-line phi expression generated by PhiMojo is not readable by a human

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo#2777] opened 2024-01-15 09:12 UTC
Currently, we print it all in one line. It's hard to read. Would be great if we can format it somehow, by adding EOLs and TABs (two spaces) where it's appropriate.

**Comment by yegor256** [comment] 2024-01-15 09:13
@maxonfjvipon can you please help?

**Comment by maxonfjvipon** [comment] 2024-01-15 09:14
@yegor256 duplicate of #2689

**Closed** 2024-01-15 09:15 UTC
Labels: bug
