### ISSUE TITLE
`xmir-to-phi` doesn't fail on invalid attribute names

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo#3322] opened 2024-08-08 06:47 UTC
When I run `xmir-to-phi` goal I successfully convert all `xmir` files into PHI expressions. However, recently we realised that PHI expressions we get have a mistake:

```phi
I-0 ↦ Φ.org.eolang.param,
```

> AFAIK, in PHI, all attribute labels must start with a lowercase letter.

You can read more about it [here](https://github.com/objectionary/normalizer/issues/379#issuecomment-2273575804).
**Expected behaviour:** `xmir-to-phi` throws an error that is saying about the wrong naming.

Here is my configuration:
```xml
<plugin>
  <groupId>org.eolang</groupId>
  <artifactId>eo-maven-plugin</artifactId>
  <version>0.39.0</version>
  <executions>
    <execution>
      <id>convert-xmir-to-phi</id>
      <phase>process-classes</phase>
      <goals>
        <goal>xmir-to-phi</goal>
      </goals>
      <configuration>
        <phiInputDir>${opeo.modified}</phiInputDir>
        <phiOutputDir>${eo.phi.output}</phiOutputDir>
      </configuration>
    </execution>
  </executions>
</plugin>
```

**Comment by volodya-lombrozo** [comment] 2024-08-08 06:47
@maxonfjvipon Please, have a look

**Comment by yegor256** [comment] 2024-10-14 10:50
@maxonfjvipon would be great to add a check into xmir-to-phi, to fail faster

**Comment by yegor256** [comment] 2024-12-03 12:12
@maxonfjvipon @volodya-lombrozo now, we don't fail at all: this is by design. If you want to check the quality/validity of XMIR, use `lint` goal of our Maven plugin.

**Comment by yegor256** [comment] 2024-12-15 05:08
@volodya-lombrozo I'm closing this, since all validations of XMIR/EO are moved to linters, which must be executed separately

**Closed by yegor256** 2024-12-15 05:08 UTC
Labels: bug, help wanted, good first issue
