### ISSUE TITLE
eoc compilation can be called from several processes.

### ISSUE THREAD

**Issue by levBagryansky** [objectionary/eo#2311] opened 2023-07-25 09:34 UTC
Formally, the eo compiler can be started simultaneously from some directories. That is, there will be several of eo compiling processes that do not know about each other. However they interact with the same `./eo` cache directory. I think this case must be considered,
@yegor256 @volodya-lombrozo please take a look

**Comment by volodya-lombrozo** [comment] 2023-07-26 14:55
@levBagryansky Do you think we will get any performance improvement from it?

**Comment by levBagryansky** [comment] 2023-07-26 15:11
@volodya-lombrozo I don't suggest to compile this way but user can call `eoc` from several directories at the one time, For instance he has tree
```
├── app1/app1.eo
├── app2/app2.eo
```
He can run `eoc app1.eo` in `app1/` and `eoc app2.eo` in `app2/`. So we need to think of this case

**Comment by volodya-lombrozo** [comment] 2023-07-26 17:41
@levBagryansky I see. Actually it is a good idea. Although I don't think that it is a first priority task at least for now.
By the way, have you faced with that problem in real life? Some real case?

**Comment by yegor256** [comment] 2023-07-26 18:07
@levBagryansky indeed, we need to specify a problem that might show up. Even better, we should give a real scenario and an error message.

**Comment by yegor256** [comment] 2024-10-14 11:17
@levBagryansky it's a duplicate of #2857

**Closed by yegor256** 2024-10-14 11:17 UTC
